"""Tipos de fila en tabla reglas (HU-GRC-01)."""

EXCLUSION_ESTADO = "EXCLUSION_ESTADO"
EXCLUSION_TIPO_OPER = "EXCLUSION_TIPO_OPER"
MORA_TEMPRANA_DIAS_MIN = "MORA_TEMPRANA_DIAS_MIN"
MORA_TEMPRANA_DIAS_MAX = "MORA_TEMPRANA_DIAS_MAX"

TIPOS_MORA_TEMPRANA = frozenset(
    {
        EXCLUSION_ESTADO,
        EXCLUSION_TIPO_OPER,
        MORA_TEMPRANA_DIAS_MIN,
        MORA_TEMPRANA_DIAS_MAX,
    }
)
